name: copy_to_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^9.0.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  gap: ^3.0.0
  go_router: ^7.0.1
  hexcolor: ^3.0.1
  intl: ^0.18.0
  jiffy: ^6.1.0
  logger: ^1.3.0
  octo_image: ^1.0.2
  reactive_forms: ^15.0.0
  sqflite: ^2.2.8+4

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/tabbar/
    - assets/images/common/
